# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

production:
  secret_key_base: facab7374685d27937d062af5ade1c2d2d174411c030b4c3837b29528217877977cced6404f41a51c7f805180e79b6eb3d127ea705334e81b8bf16bb5976b972



test:
  secret_key_base: 4f86827e17232e312b93637923d41afabba306d44700e8b21daac9d1708ba29d1bcd0912f59a51204195499f98f3ac7c423b8939d9fea79c4b194e1a9dc5b805

# Do not keep production secrets in the repository,
# instead read values from the environment.

development: 
#secret_key_baseENV <%  ["SECRET_KEY_BASE"] %>
  secret_key_base: e62492c34f65ef76d4d1c6688869fd9c3d0cb2936cf5357f191216fbabebb3500b73d5a66f6f81653b52c17280a8c011c4e0cbd57de0c1864ec7159cfbae8cd1
#secret_key_base: facab7374685d27937d062af5ade1c2d2d174411c030b4c3837b29528217877977cced6404f41a51c7f805180e79b6eb3d127ea705334e81b8bf16bb5976b972
#development:

#export GMAIL_USERNAME= "boltster"
#export GMAIL_PASSWORD= "'v9v9sh77vv!!$'"


#export MAILCHIMP_LIST_ID= "56be5ebcef"
#export MAILCHIMP_API_KEY= "7308b2ceb43c0d2033740dd8565804f1-us10"
#domain_name= example.com
#secret_key_base: come_to_code_with_me

#3test:

#secret_key_base: come_to_code_with_me

